#!/usr/bin/env python
from hostlists import *
import optparse

if __name__ == "__main__":
    parser = optparse.OptionParser(usage="usage: %prog [options] plugin:parameters")
    parser.add_option("-s","--sep",dest="sep",default=',',help="Separator character, default=\",\"")
    parser.add_option("--onepass",dest="onepass",default=False,action="store_true")
    parser.add_option("--expand","-e",dest="expand",default=False,action="store_true",help="Expand the host list and display one host per line")
    (options, args) = parser.parse_args()
    range=range_split(','.join(args))
    if options.expand:
        print '\n'.join(expand(range,onepass=options.onepass))
    else:
        print ', '.join(compress(expand(range,onepass=options.onepass)))
    
